# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider :virtualbox do |vb|
	vb.customize [ 'modifyvm', :id, '--name', 'demo-00' ]
        vb.customize [ 'modifyvm', :id, '--cpus', 1 ]
        vb.customize [ 'modifyvm', :id, '--memory', 420 ]
	vb.customize [ 'modifyvm', :id, '--cpuexecutioncap', 70 ]

  end
end

